# Generated by Django 2.0.5 on 2018-06-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180627_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='musician',
            name='birthday',
            field=models.DateField(),
        ),
    ]
