# Generated by Django 2.0.5 on 2018-06-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180627_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.TimeField(),
        ),
    ]
