# Generated by Django 2.0.5 on 2018-06-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180627_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.DurationField(),
        ),
    ]
